#!/usr/bin/env bash
# probe-lead.sh — measure, live, the mod-API levers the panel would build on.
#
# The mod API documents four model-facing levers ($.prompt.submit,
# $.tool.register served by a tool.call hook, a prompt.compose section,
# $.store) — documented, not measured. This runner generates a tiny probe mod
# under its work dir (never shipped, never committed), starts an interactive
# `claude --plugin-dir` on it inside a dedicated tmux server (never the
# user's), and drives one check per lever:
#
#   A1  idle wake      a $.prompt.submit 15 s after session.start must start
#                      a turn with no keystroke; the transcript row is told
#                      apart from a typed prompt; the person's
#                      UserPromptSubmit settings hook (a one-line logging
#                      hook in the isolated config) fires for it or not.
#   A2  busy wake      submits during a running turn must not be dropped:
#                      each runs as its own turn after the first ends; two
#                      back-to-back submits are recorded as merged or
#                      stacked.
#   A3  store resume   $.store.set in one process is read back at
#                      session.start of a `--resume` of the same session id;
#                      $.session.id() must be equal in both.
#   A4  tool           a tool registered at session.start and served by a
#                      tool.call hook must reach the model as ECHO:<text>.
#   A5  system section a prompt.compose section must reach the model.
#
#   probe-lead.sh wake    a second mode: the live wake check against the REAL
#                         mod. A fake `outsource` binary serves the committed
#                         fixtures, one own row flips running→done
#                         mid-session, and the idle session must start a turn
#                         by itself whose transcript row holds the
#                         [outsource-panel] text.
#   probe-lead.sh A2 A4   only those checks (default: all of A1–A5).
#
# Evidence: the session transcript jsonl under the isolated config dir plus
# tmux captures, both under the work dir (default mktemp; PROBE_LEAD_OUT
# overrides). One attempt per check; each verdict is MATCH or MISMATCH with
# one evidence line.
#
# Sessions run --permission-mode bypassPermissions (the real lead's mode; in
# default mode a permission dialog reads as "busy" or "tool failed"), with
# the bypass confirmation pre-accepted in the isolated config the same way as
# the trust dialog; a dialog that still appears is a recorded finding, named
# and dismissed, never a verdict. ANTHROPIC_BASE_URL / ANTHROPIC_AUTH_TOKEN
# are inherited from the caller and never printed; the model is pinned to
# glm-5.3. The tmux server is killed on exit; only pids captured at start are
# ever signalled.
set -uo pipefail

MOD="$(cd "$(dirname "$0")/.." && pwd)"
SRV="outsource-lead-probe"
WD="${PROBE_LEAD_OUT:-$(mktemp -d "${TMPDIR:-/tmp}/outsource-lead-probe.XXXXXX")}"
CFG="$WD/cfg"
WORK="$WD/work"
CAPS="$WD/captures"
PROBE="$WD/probe-mod"
UPS_LOG="$WD/userprompts.log"
MODEL_ENV=(
  ANTHROPIC_MODEL=glm-5.3
  ANTHROPIC_DEFAULT_OPUS_MODEL=glm-5.3
  ANTHROPIC_DEFAULT_SONNET_MODEL=glm-5.3
  ANTHROPIC_DEFAULT_HAIKU_MODEL=glm-5.3
  ANTHROPIC_SMALL_FAST_MODEL=glm-5.3
  CLAUDE_CODE_SUBAGENT_MODEL=glm-5.3
)
mkdir -p "$CFG" "$WORK" "$CAPS" "$PROBE/hooks" "$PROBE/.claude-plugin"

cleanup() {
  tmux -L "$SRV" kill-server >/dev/null 2>&1 || true
  for f in "$WD"/*.pid; do
    [ -f "$f" ] || continue
    kill "$(cat "$f")" >/dev/null 2>&1 || true
  done
  echo "evidence: $WD"
}
trap cleanup EXIT

# ---- recorders ----------------------------------------------------------------

declare -a CHECKS=()
declare -a VERDICTS=()
declare -a NOTES=()
record() { # <MATCH|MISMATCH> <check> <evidence line>
  CHECKS+=("$2")
  VERDICTS+=("$1")
  NOTES+=("$3")
  printf '%s  %s  %s\n' "$1" "$2" "$3"
}

# ---- the generated probe mod --------------------------------------------------

cat >"$PROBE/.claude-plugin/plugin.json" <<'EOF'
{
  "name": "lead-probe",
  "version": "0.1.0",
  "description": "Measures the mod-API levers the outsource panel builds on. Generated by probe-lead.sh; never shipped.",
  "author": {
    "name": "outsource-panel tools"
  }
}
EOF
cat >"$PROBE/hooks/hooks.json" <<'EOF'
{
  "modules": ["./register.js"]
}
EOF
cat >"$PROBE/hooks/register.js" <<'EOF'
// lead-probe: one hook per lever probe-lead.sh measures. The A1 timer fires
// 15 s after session.start, so the session must sit idle until then.
export const register = (on) => {
  on('session.start', async ($, e, next) => {
    const sid = await $.session.id()
    await $.command.register({
      name: 'probe',
      description: 'Drive the lead-probe measurements',
      argumentHint: 'wake <text> | store',
      immediate: true,
    })
    let toolNote = ''
    try {
      await $.tool.register({
        name: 'probe_echo',
        description: 'Echoes its text back prefixed with ECHO:.',
        inputSchema: {
          type: 'object',
          properties: { text: { type: 'string', description: 'the text to echo' } },
          required: ['text'],
        },
      })
    } catch (err) {
      toolNote = ' TOOL-REGISTER-FAILED:' + (err instanceof Error ? err.message : String(err))
    }
    const stored = await $.store.get('probe')
    if (stored !== undefined) {
      const same = typeof stored === 'object' && stored !== null && stored.sid === sid
      const line =
        'PROBE-STORE-READBACK stored=' + JSON.stringify(stored) + ' currentSid=' + sid + ' sameSid=' + same
      $.ui.toast(line)
      $.ui.log(line)
      try {
        await $.session.append({
          message: { type: 'system', content: [{ type: 'text', text: line }] },
        })
      } catch {
        // the toast and the debug log still carry it
      }
    }
    $.ui.toast('PROBE-START sid=' + sid + toolNote)
    $.ui.log('PROBE-START sid=' + sid + toolNote)
    const noA1 = (await $.env.get('OUTSOURCE_PROBE_NO_A1')) !== undefined
    if (!noA1) {
      $.clock.after(15000, () => {
        void $.prompt
          .submit({ text: 'PROBE-WAKE-A1: reply with the exact first line of this message and say who sent it.' })
          .then(() => $.ui.log('PROBE-A1 submit resolved'))
          .catch((err) => $.ui.log('PROBE-A1 submit rejected: ' + (err instanceof Error ? err.message : String(err))))
      })
    }
    return next(e)
  })

  on('command.run', { command: 'probe' }, async ($, e) => {
    const args = (e.args ?? '').trim()
    if (args === 'store') {
      const sid = await $.session.id()
      const t = await $.clock.now()
      await $.store.set('probe', { sid, t })
      return { text: 'PROBE-STORE-SET ' + JSON.stringify({ sid, t }) }
    }
    // Kept for the record: a submit from a command.run hook while a turn
    // runs is refused by a host check (measured 2026-10-06, run 1: "it
    // would wait on the turn this hook is holding"). The busy-wake A2
    // measures the timer path instead.
    if (args.startsWith('wake ')) {
      try {
        await $.prompt.submit({ text: args.slice('wake '.length) })
        return { text: 'PROBE submitted' }
      } catch (err) {
        return { text: 'PROBE wake FAILED: ' + (err instanceof Error ? err.message : String(err)) }
      }
    }
    return { text: 'usage: /probe wake <text> | store' }
  })

  on('tool.call', { tool: 'mcp__lead-probe__probe_echo' }, ($, e) => {
    return { result: 'ECHO:' + String(e.text ?? '') }
  })

  on('prompt.compose', ($, e, next) =>
    next(e).then((base) => ({
      sections: [
        ...base.sections,
        { id: 'probe-lead', text: 'The probe token is PROBE-SYS-A5.', scope: 'session' },
      ],
    })),
  )

  on('prompt.submit', ($, e, next) => {
    $.ui.log(
      'PROBE-EV prompt.submit origin=' +
        JSON.stringify(e.origin) +
        ' wait=' +
        e.wait +
        ' text=' +
        JSON.stringify(String(e.text ?? '').slice(0, 80)),
    )
    // A2: a busy turn is typed; six seconds in (inside its sleep 25), a
    // timer submits the wake. Measured 2026-10-06: the same submit from a
    // command.run hook is refused by a host check ("it would wait on the
    // turn this hook is holding"), so the timer is the only measured path.
    const text = String(e.text ?? '')
    if (text.includes('PROBE-BUSY-A2 ')) {
      $.clock.after(6000, () => {
        void $.prompt
          .submit({ text: 'PROBE-WAKE-A2: reply with the single word WOKE.' })
          .then(() => $.ui.log('PROBE-A2 submit resolved'))
          .catch((err) => $.ui.log('PROBE-A2 submit rejected: ' + (err instanceof Error ? err.message : String(err))))
      })
    }
    if (text.includes('PROBE-BUSY-A2BC')) {
      $.clock.after(6000, () => {
        void $.prompt
          .submit({ text: 'PROBE-WAKE-A2b: reply with the single word BEE.' })
          .then(() => $.prompt.submit({ text: 'PROBE-WAKE-A2c: reply with the single word CEE.' }))
          .then(() => $.ui.log('PROBE-A2bc both resolved'))
          .catch((err) => $.ui.log('PROBE-A2bc rejected: ' + (err instanceof Error ? err.message : String(err))))
      })
    }
    return next(e)
  })
}
EOF

# ---- the isolated config ------------------------------------------------------

# Seed the config dir so no onboarding, trust or bypass dialog blocks the
# session: hasCompletedOnboarding + hasTrustDialogAccepted (both spellings of
# the workspace path, macOS resolves /tmp through /private/tmp) plus
# bypassPermissionsModeAccepted for --permission-mode bypassPermissions.
seed_cfg() {
  mkdir -p "$CFG"
  local phys
  phys="$(python3 -c 'import os, sys; print(os.path.realpath(sys.argv[1]))' "$WORK")"
  {
    printf '{"hasCompletedOnboarding": true, "autoUpdates": false, "bypassPermissionsModeAccepted": true, "projects": {\n'
    printf '  "%s": {"hasTrustDialogAccepted": true},\n' "$WORK"
    printf '  "%s": {"hasTrustDialogAccepted": true}\n' "$phys"
    printf '}}\n'
  } >"$CFG/.claude.json"
  # A1's settings-hook question: does a plugin-submitted prompt fire the
  # person's UserPromptSubmit hooks? One line per firing, timestamped.
  python3 - "$UPS_LOG" >"$CFG/settings.json" <<'PY'
import json, sys

print(json.dumps({
    "hooks": {
        "UserPromptSubmit": [
            {
                "hooks": [
                    {
                        "type": "command",
                        "command": "printf '%s\\n' \"UPS $(date +%s)\" >> " + sys.argv[1],
                    }
                ]
            }
        ]
    }
}))
PY
}
seed_cfg

# ---- tmux helpers -------------------------------------------------------------

# What a blocking dialog looks like. Measured: with bypassPermissionsModeAccepted
# pre-seeded there is no bypass dialog at all — the status line reading
# "bypass permissions on" is exactly that, a status line, and must not match
# (it matched in the first run and cost A1 its wait_ready).
DIALOG_PAT='Quick safety check|trust this folder|choose a theme|select a theme|bypass permissions mode|accept the risk'

cap() { tmux -L "$SRV" capture-pane -p -t "$2" >"$CAPS/$1.txt" 2>/dev/null || true; }
pane() { tmux -L "$SRV" capture-pane -p -t "$1" 2>/dev/null || true; }
send_keys() { tmux -L "$SRV" send-keys -t "$2" -l "$1"; }
enter() { tmux -L "$SRV" send-keys -t "$1" Enter; }

# The probe session must not inherit this delegate's own inbox socket or
# session markers; the auth env is inherited untouched.
start_session() { # <name> [extra claude args...]
  local name="$1"
  shift
  tmux -L "$SRV" new-session -d -s "$name" -x 160 -y 50 -c "$WORK" \
    "env -u CLAUDE_CODE_MESSAGING_SOCKET -u CLAUDE_CODE_MESSAGING_TOKEN -u CLAUDE_CODE_SESSION_ID -u CLAUDE_CODE_CHILD_SESSION -u OUTSOURCE_ROUND -u OUTSOURCE_DETACHED CLAUDE_CONFIG_DIR='$CFG' ${MODEL_ENV[*]} claude --plugin-dir '$PROBE' --permission-mode bypassPermissions --debug-file '$WD/debug-$name.log' $*"
}

dialog_is_up() { printf '%s' "$1" | grep -qiE "$DIALOG_PAT"; }

dismiss_dialog() { # <session> — at most 2 attempts, recorded; Down+Enter so a
  # trust prompt lands on "Yes", never on the highlighted "No, exit".
  local attempt name="$1" seen="" shot
  for attempt in 1 2; do
    shot="$(pane "$name")"
    if dialog_is_up "$shot"; then
      seen="dialog dismissed (attempt $attempt): $(printf '%s' "$shot" | grep -iE 'safety|trust|theme|bypass|risk' | head -1 | cut -c1-70)"
      tmux -L "$SRV" send-keys -t "$name" Down
      sleep 0.3
      enter "$name"
      sleep 2
      continue
    fi
    break
  done
  [ -n "$seen" ] && echo "  note: $seen" || true
}

wait_ready() { # <session> — until the capture is stable and shows a prompt
  local prev="" cur=""
  for _ in $(seq 1 60); do
    sleep 1
    cur="$(pane "$1")"
    if [ -n "$cur" ] && [ "$cur" = "$prev" ] && printf '%s' "$cur" | grep -qE '[?❯>│]' && ! dialog_is_up "$cur"; then
      return 0
    fi
    prev="$cur"
  done
  return 1
}

# ---- transcript helpers -------------------------------------------------------

# BSD find wants -maxdepth right after the path (measured: with it last,
# sessions_dir returned nothing and every transcript wait failed).
sessions_dir() { find "$CFG" -maxdepth 3 -type d -name projects 2>/dev/null | head -1; }

# The newest transcript holding <marker> in a row that does not hold
# <exclude> (the typed /probe command row carries the markers it orders);
# prints its path. Transcripts sit one slug deeper than the projects dir
# (projects/<cwd-slug>/<session>.jsonl — measured run 3, where a flat glob
# found nothing and every wait failed on a working session).
transcript_with() { # <marker> [exclude]
  local d f
  d="$(sessions_dir)"
  [ -n "$d" ] || return 1
  for f in "$d"/*/*.jsonl "$d"/*.jsonl; do
    [ -f "$f" ] || continue
    if python3 -c '
import sys

marker, exclude, path = sys.argv[1], sys.argv[2], sys.argv[3]
for line in open(path, encoding="utf-8", errors="replace"):
    if marker in line and (not exclude or exclude not in line):
        sys.exit(0)
sys.exit(1)' "$1" "${2:-}" "$f"; then
      printf '%s' "$f"
      return 0
    fi
  done
  return 1
}

# Wait until some transcript holds <marker> in a row that is not the typed
# /probe command row; prints its path. The exclude marker makes a dropped
# submit distinguishable from the command that ordered it.
wait_transcript() { # <marker> <ceiling-seconds> [exclude]
  local f waited=0
  while [ "$waited" -lt "$2" ]; do
    sleep 2
    waited=$((waited + 2))
    if f="$(transcript_with "$1" "${3:-}")"; then printf '%s' "$f"; return 0; fi
  done
  return 1
}

# True when a row of <type> holding <marker> exists (a verdict condition:
# assistant rows appear only once the model has actually answered, which a
# one-shot grep races — measured runs 3–4).
has_row_of_type() { # <transcript> <type> <marker>
  python3 - "$1" "$2" "$3" <<'PY'
import json, sys

path, want, marker = sys.argv[1], sys.argv[2], sys.argv[3]
for line in open(path, encoding="utf-8", errors="replace"):
    if marker not in line:
        continue
    try:
        row = json.loads(line)
    except Exception:
        continue
    if row.get("type") == want:
        sys.exit(0)
sys.exit(1)
PY
}

# Wait until a row of <type> holding <marker> exists; prints the transcript.
wait_row_of_type() { # <marker> <type> <ceiling-seconds> [exclude]
  local f waited=0
  while [ "$waited" -lt "$3" ]; do
    sleep 3
    waited=$((waited + 3))
    if f="$(transcript_with "$1" "${4:-}")"; then
      if has_row_of_type "$f" "$2" "$1"; then printf '%s' "$f"; return 0; fi
    fi
  done
  return 1
}

# The transcript row shape: type, isMeta and the origin/plugin fields, plus
# where the text sits — the exact row a $.prompt.submit becomes. The first
# holder of a marker is often a bookkeeping row (queue-operation,
# last-prompt); the shape that matters is the user row the model reads, so
# want-type narrows it.
row_shape() { # <transcript> <marker> [want-type]
  python3 - "$1" "$2" "${3:-}" <<'PY'
import json, sys

path, marker, want = sys.argv[1], sys.argv[2], sys.argv[3]
for line in open(path, encoding="utf-8"):
    if marker not in line:
        continue
    try:
        row = json.loads(line)
    except Exception:
        continue
    if want and row.get("type") != want:
        continue
    keys = sorted(row.keys())
    msg = row.get("message") if isinstance(row.get("message"), dict) else {}
    content = msg.get("content")
    texts = []
    if isinstance(content, str):
        texts = [content[:100]]
    elif isinstance(content, list):
        for b in content:
            if isinstance(b, dict) and b.get("type") == "text":
                texts.append(str(b.get("text"))[:100])
    origin = row.get("origin") or row.get("pluginMeta") or row.get("source")
    print(f"row keys: {keys}")
    print(f"type={row.get('type')} isMeta={row.get('isMeta')} origin={json.dumps(origin)[:160]}")
    print(f"text[0]={texts[0] if texts else None!r}")
    break
PY
}

# The first assistant text after the last user-role row holding <marker>
# (the answer often quotes the marker itself, so scanning past the marker's
# last occurrence — last-prompt bookkeeping included — finds nothing).
answer_after() { # <transcript> <marker>
  python3 - "$1" "$2" <<'PY'
import json, sys

path, marker = sys.argv[1], sys.argv[2]
rows = []
for line in open(path, encoding="utf-8", errors="replace"):
    if marker not in line:
        rows.append(None)
        continue
    try:
        rows.append(json.loads(line))
    except Exception:
        rows.append(None)
last = -1
for i, row in enumerate(rows):
    if row is not None and row.get("type") == "user":
        last = i
for row in rows[last + 1:]:
    if not isinstance(row, dict) or row.get("type") != "assistant":
        continue
    msg = row.get("message") or {}
    for b in msg.get("content") or []:
        if isinstance(b, dict) and b.get("type") == "text" and b.get("text", "").strip():
            print(b["text"][:300].replace("\n", " "))
            sys.exit(0)
print("(no assistant text after the marker)")
PY
}

ups_count() { [ -f "$UPS_LOG" ] && wc -l <"$UPS_LOG" | tr -d ' ' || echo 0; }

# ---- checks -------------------------------------------------------------------

# Start session a1 if it is not up (standalone check runs). With noA1=1 the
# probe mod skips its 15 s idle-wake timer, so a standalone A2/A4/A5 run is
# not interleaved with an A1 wake.
ensure_session() { # <noA1:0|1>
  tmux -L "$SRV" has-session -t a1 2>/dev/null && return 0
  local extra=""
  [ "$1" = 1 ] && extra="OUTSOURCE_PROBE_NO_A1=1 "
  tmux -L "$SRV" new-session -d -s a1 -x 160 -y 50 -c "$WORK" \
    "env -u CLAUDE_CODE_MESSAGING_SOCKET -u CLAUDE_CODE_MESSAGING_TOKEN -u CLAUDE_CODE_SESSION_ID -u CLAUDE_CODE_CHILD_SESSION -u OUTSOURCE_ROUND -u OUTSOURCE_DETACHED ${extra}CLAUDE_CONFIG_DIR='$CFG' ${MODEL_ENV[*]} claude --plugin-dir '$PROBE' --permission-mode bypassPermissions --debug-file '$WD/debug-a1.log'"
  wait_ready a1
}

check_a1() { # idle wake: the 15 s timer's submit starts a turn by itself
  local ups0 f
  ups0="$(ups_count)" # read before launch: the submit can fire during wait_ready
  start_session a1
  if ! wait_ready a1; then
    pane a1 >"$CAPS/a1-boot.txt"
    record MISMATCH A1 "no prompt appeared within 60 s (see $CAPS/a1-boot.txt)"
    return
  fi
  dismiss_dialog a1
  # Nothing is typed: the only possible source of a turn is the timer.
  if ! f="$(wait_row_of_type 'PROBE-WAKE-A1' user 90)"; then
    cap a1 a1
    record MISMATCH A1 "no transcript user row holds PROBE-WAKE-A1 after 90 s idle"
    return
  fi
  local answer="(no assistant text within 120 s)"
  if wait_row_of_type 'PROBE-WAKE-A1' assistant 120 >/dev/null; then
    answer="$(answer_after "$f" 'PROBE-WAKE-A1')"
  fi
  cap a1 a1
  local shape ups1 why=""
  shape="$(row_shape "$f" 'PROBE-WAKE-A1' user)"
  ups1="$(ups_count)"
  {
    echo "== row shape =="
    echo "$shape"
    echo "== model answer =="
    echo "$answer"
    echo "== userprompts.log lines $ups0 -> $ups1 =="
  } >"$CAPS/a1-evidence.txt"
  printf '%s\n' "$shape" >"$WD/a1-row-shape.txt"
  if [ "$ups1" -gt "$ups0" ]; then why="UserPromptSubmit settings hook fired (+$((ups1 - ups0)))"; fi
  record MATCH A1 "turn started with no keystroke; $(echo "$shape" | sed -n 2p | cut -c1-90); answer: $(printf '%s' "$answer" | cut -c1-70); ${why:-UserPromptSubmit settings hook did not fire}"
}

check_a2() { # busy wake: not dropped, own turn after; two submits merge/stack
  local f
  ensure_session 1 || {
    record MISMATCH A2 "no prompt appeared within 60 s"
    return
  }
  dismiss_dialog a1
  send_keys 'PROBE-BUSY-A2 Run exactly this Bash command: sleep 25. Then reply with the single word SLEPT.' a1
  enter a1
  sleep 12 # the probe mod's 6 s timer submitted the wake inside the sleep
  cap a2-busy a1
  # The order verdict needs both turns' ends: the sleep turn's SLEPT answer
  # and the wake's own user row.
  if ! f="$(wait_row_of_type 'PROBE-WAKE-A2:' user 120 'PROBE-BUSY-A2')"; then
    record MISMATCH A2 "PROBE-WAKE-A2 never reached a transcript user row (dropped or refused; see $WD/debug-a1.log)"
    return
  fi
  if ! wait_row_of_type 'SLEPT' assistant 120 >/dev/null; then
    record MISMATCH A2 "the sleep turn never produced its SLEPT answer"
    return
  fi
  cap a2 a1
  python3 - "$f" >"$CAPS/a2-evidence.txt" <<'PY'
import json, sys

path = sys.argv[1]
rows = []
for i, line in enumerate(open(path, encoding="utf-8")):
    try:
        row = json.loads(line)
    except Exception:
        continue
    t = row.get("type")
    if t == "user" and "PROBE-BUSY-A2 " in line and "SLEPT" in line:
        rows.append((i, "sleep-prompt"))
    elif t == "assistant" and "SLEPT" in line:
        rows.append((i, "slept-answer"))
    elif t == "user" and "PROBE-WAKE-A2:" in line:
        rows.append((i, "wake-row"))
for r in rows:
    print(r)

names = [name for _, name in rows]

def idx(name):
    return names.index(name) if name in names else -1

ok = idx("sleep-prompt") >= 0 and idx("slept-answer") > idx("sleep-prompt") and idx("wake-row") > idx("slept-answer")
print("ORDER", "ok: the sleep turn ended before the wake turn started" if ok else "unexpected")
PY
  local order
  order="$(tail -1 "$CAPS/a2-evidence.txt")"
  if [ "$order" = "ORDER ok: the sleep turn ended before the wake turn started" ]; then
    record MATCH A2 "not dropped: queued behind the running turn, ran as its own turn after it"
  else
    record MISMATCH A2 "$order ($(grep -c 'wake-row' "$CAPS/a2-evidence.txt" || true) wake rows)"
  fi

  # A2b/A2c: two submits back to back during one busy turn.
  send_keys 'PROBE-BUSY-A2BC Run exactly this Bash command: sleep 25. Then reply with the single word NAP.' a1
  enter a1
  sleep 12
  if ! f="$(wait_row_of_type 'PROBE-WAKE-A2c' user 120 'PROBE-BUSY-A2BC')"; then
    record MISMATCH "A2b/c" "PROBE-WAKE-A2c never reached a transcript user row"
    return
  fi
  sleep 15
  cap a2bc a1
  python3 - "$f" >"$CAPS/a2bc-evidence.txt" <<'PY'
import json, sys

path = sys.argv[1]
rows = []
for i, line in enumerate(open(path, encoding="utf-8")):
    if "PROBE-BUSY" in line:
        continue
    if "PROBE-WAKE-A2b" not in line and "PROBE-WAKE-A2c" not in line:
        continue
    try:
        row = json.loads(line)
    except Exception:
        continue
    # Only user rows are turns: queue-operation and last-prompt are
    # bookkeeping around them.
    if row.get("type") != "user":
        continue
    rows.append(("user", "A2b" if "PROBE-WAKE-A2b" in line else "", "A2c" if "PROBE-WAKE-A2c" in line else ""))
for r in rows:
    print("row", r)
if len(rows) == 0:
    print("verdict: DELIVERED NOWHERE")
elif len(rows) == 1:
    print("verdict: MERGED into one user row")
else:
    print(f"verdict: STACKED as {len(rows)} user rows")
PY
  local shape_note
  shape_note="$(tail -1 "$CAPS/a2bc-evidence.txt")"
  case "$shape_note" in
    "verdict: MERGED into one user row" | "verdict: STACKED as "*)
      record MATCH "A2b/c" "both delivered — ${shape_note#verdict: }"
      ;;
    *)
      record MISMATCH "A2b/c" "${shape_note#verdict: }"
      ;;
  esac
}

check_a4() { # the registered tool reaches the model
  local f
  ensure_session 1 || {
    record MISMATCH A4 "no prompt appeared within 60 s"
    return
  }
  dismiss_dialog a1
  send_keys 'Call the tool probe_echo (its full name is mcp__lead-probe__probe_echo) with text hello-tool. Then reply with exactly the text the tool returned, nothing else.' a1
  enter a1
  if ! f="$(wait_row_of_type 'ECHO:hello-tool' user 120)"; then
    cap a4 a1
    record MISMATCH A4 "no transcript row holds ECHO:hello-tool (see $CAPS/a4.txt)"
    return
  fi
  if ! wait_row_of_type 'ECHO:hello-tool' assistant 120 >/dev/null; then
    cap a4 a1
    record MISMATCH A4 "the tool result row exists but no assistant row quotes it (see $CAPS/a4.txt)"
    return
  fi
  cap a4 a1
  # The typed prompt names the tool too; the rows that matter are the
  # tool_use block and the tool_result block, not the user row.
  local tool_row result_row
  tool_row="$(grep -m1 -E 'tool_use.{0,200}probe_echo' "$f" | python3 -c 'import json,sys
try:
    row = json.loads(sys.stdin.read())
    msg = row.get("message") or {}
    print(row.get("type"), json.dumps(msg.get("content"))[:220])
except Exception as e:
    print("(unparseable)", e)')"
  result_row="$(grep -m1 'ECHO:hello-tool' "$f" | python3 -c 'import json,sys
try:
    row = json.loads(sys.stdin.read())
    msg = row.get("message") or {}
    print(row.get("type"), json.dumps(msg.get("content"))[:220])
except Exception as e:
    print("(unparseable)", e)')"
  local answer
  answer="$(answer_after "$f" 'ECHO:hello-tool')"
  {
    echo "tool_use row: $tool_row"
    echo "tool_result row: $result_row"
    echo "model answer: $answer"
  } >"$CAPS/a4-evidence.txt"
  if printf '%s' "$answer" | grep -q 'ECHO:hello-tool'; then
    record MATCH A4 "tool result reached the model; it answered: $(printf '%s' "$answer" | cut -c1-70)"
  else
    record MISMATCH A4 "result row exists but the model did not quote it: $(printf '%s' "$answer" | cut -c1-70)"
  fi
}

check_a5() { # the prompt.compose section reaches the model
  ensure_session 1 || {
    record MISMATCH A5 "no prompt appeared within 60 s"
    return
  }
  dismiss_dialog a1
  send_keys 'What is the probe token? Reply with the token only, nothing else.' a1
  enter a1
  if ! wait_row_of_type 'PROBE-SYS-A5' assistant 120 >/dev/null; then
    cap a5 a1
    record MISMATCH A5 "no assistant row holds PROBE-SYS-A5 (see $CAPS/a5.txt)"
    return
  fi
  cap a5 a1
  record MATCH A5 "the model answered with the section token (assistant row holds PROBE-SYS-A5)"
}

check_a3() { # $.store across quit and --resume of the same session id
  local f sid set_line
  ensure_session 1 || {
    record MISMATCH A3 "no prompt appeared within 60 s"
    return
  }
  dismiss_dialog a1
  send_keys '/probe store' a1
  enter a1
  if ! f="$(wait_transcript 'PROBE-STORE-SET' 60)"; then
    record MISMATCH A3 "'/probe store' left no transcript trace"
    return
  fi
  sleep 3
  cap a3-set a1
  # The pane prints the command's own reply; the transcript stores it in a
  # system row with the text in a different field, so the pane line is the
  # primary source and the transcript the fallback.
  set_line="$(pane a1 | grep -m1 'PROBE-STORE-SET' || true)"
  sid="$(printf '%s' "$set_line" | sed -n 's/.*"sid":"\([^"]*\)".*/\1/p')"
  if [ -z "$sid" ]; then
    sid="$(python3 -c '
import json, re, sys

def texts(row):
    msg = row.get("message") or {}
    c = msg.get("content")
    if isinstance(c, str):
        yield c
    elif isinstance(c, list):
        for b in c:
            if isinstance(b, dict) and isinstance(b.get("text"), str):
                yield b["text"]

for line in open(sys.argv[1], encoding="utf-8", errors="replace"):
    if "PROBE-STORE-SET" not in line:
        continue
    try:
        row = json.loads(line)
    except Exception:
        continue
    for t in texts(row):
        m = re.search(r"\{.*\}", t)
        if not m:
            continue
        try:
            sid = json.loads(m.group(0)).get("sid")
        except Exception:
            continue
        if isinstance(sid, str) and sid:
            print(sid)
            sys.exit(0)
sys.exit(1)' "$f" || true)"
  fi
  if [ -z "$sid" ]; then
    record MISMATCH A3 "could not read the session id from the transcript (pane: $set_line)"
    return
  fi
  send_keys '/exit' a1
  enter a1
  sleep 3
  # Resume the same session id with the same probe mod.
  tmux -L "$SRV" kill-session -t a1 2>/dev/null || true
  tmux -L "$SRV" new-session -d -s a3 -x 160 -y 50 -c "$WORK" \
    "env -u CLAUDE_CODE_MESSAGING_SOCKET -u CLAUDE_CODE_MESSAGING_TOKEN -u CLAUDE_CODE_SESSION_ID -u CLAUDE_CODE_CHILD_SESSION -u OUTSOURCE_ROUND -u OUTSOURCE_DETACHED CLAUDE_CONFIG_DIR='$CFG' ${MODEL_ENV[*]} claude --resume '$sid' --plugin-dir '$PROBE' --permission-mode bypassPermissions --debug-file '$WD/debug-a3.log'"
  if ! wait_ready a3; then
    record MISMATCH A3 "the resumed session never showed a prompt"
    return
  fi
  dismiss_dialog a3
  if ! f="$(wait_transcript 'PROBE-STORE-READBACK' 60)"; then
    cap a3 a3
    record MISMATCH A3 "no PROBE-STORE-READBACK row after resume (see $CAPS/a3.txt)"
    return
  fi
  cap a3 a3
  local line
  # A session.append notice is a system row: the text sits in the top-level
  # content field, not under message.
  line="$(grep -m1 'PROBE-STORE-READBACK' "$f" | python3 -c 'import json,sys
try:
    row = json.loads(sys.stdin.read())
    c = row.get("content")
    if not isinstance(c, str):
        msg = row.get("message") or {}
        c = msg.get("content")
    text = c if isinstance(c, str) else " ".join(str(b.get("text")) for b in (c or []) if isinstance(b, dict))
    print(text[:220])
except Exception:
    print("(unparseable)")')"
  echo "$line" >"$CAPS/a3-evidence.txt"
  if printf '%s' "$line" | grep -q 'sameSid=true' && printf '%s' "$line" | grep -q "\"sid\":\"$sid\""; then
    record MATCH A3 "store survived the restart; resumed session id is the same: $(printf '%s' "$line" | cut -c1-120)"
  else
    record MISMATCH A3 "$line"
  fi
}

# ---- the wake mode: the real mod, a fake registry, a flipped row -------------

check_wake() {
  local FIX="$WD/fixtures" UUID FAKE="$MOD/tests/fixtures/fake-outsource.sh"
  mkdir -p "$FIX"
  cp "$MOD"/tests/fixtures/runs.json "$FIX"/
  cp "$MOD"/tests/fixtures/tail-*.txt "$FIX"/
  # The flipped variant: r05 (quota-report, own, running) goes done rc=0,
  # finished 60 s before "now" in the fixture's own time base (the fake
  # binary rebases startedAt/finishedAt against NOW0).
  python3 - "$FIX/runs.json" "$FIX/runs-done.json" <<'PY'
import json, sys

rows = json.load(open(sys.argv[1]))
out = []
for r in rows:
    r = dict(r)
    if r["id"] == "r05":
        r.update(state="done", rc=0, pid=None, finishedAt=1791300000 - 60,
                 elapsedSeconds=3665, idleSeconds=None)
    out.append(r)
json.dump(out, open(sys.argv[2], "w"), ensure_ascii=False)
PY
  UUID="$(uuidgen | tr 'A-Z' 'a-z')"
  tmux -L "$SRV" kill-session -t wake >/dev/null 2>&1 || true
  tmux -L "$SRV" new-session -d -s wake -x 160 -y 50 -c "$WORK" \
    "env -u CLAUDE_CODE_MESSAGING_SOCKET -u CLAUDE_CODE_MESSAGING_TOKEN -u CLAUDE_CODE_SESSION_ID -u CLAUDE_CODE_CHILD_SESSION -u OUTSOURCE_ROUND -u OUTSOURCE_DETACHED CLAUDE_CONFIG_DIR='$CFG' OUTSOURCE_PANEL_BIN='$FAKE' OUTSOURCE_PANEL_FIXTURE_DIR='$FIX' OUTSOURCE_PANEL_OWNER='$UUID' ${MODEL_ENV[*]} claude --plugin-dir '$MOD' --session-id '$UUID' --permission-mode bypassPermissions --debug-file '$WD/debug-wake.log'"
  if ! wait_ready wake; then
    record MISMATCH WAKE "the panel session never showed a prompt"
    return
  fi
  dismiss_dialog wake
  # A fresh session id has no watermark: let the first polls pass (seed +
  # watermark) before flipping the fixture.
  sleep 14
  cp "$FIX/runs-done.json" "$FIX/runs.json"
  local f
  if ! f="$(wait_transcript '[outsource-panel] 1 of your rounds changed state' 90)"; then
    cap wake wake
    record MISMATCH WAKE "no transcript row holds the [outsource-panel] wake text (see $CAPS/wake.txt and $WD/debug-wake.log)"
    return
  fi
  cap wake wake
  python3 - "$f" >"$CAPS/wake-evidence.txt" <<'PY'
import json, sys

for line in open(sys.argv[1], encoding="utf-8", errors="replace"):
    if "[outsource-panel]" not in line:
        continue
    try:
        row = json.loads(line)
    except Exception:
        continue
    # The first holder is the queue record; the turn is the user row.
    if row.get("type") != "user":
        continue
    msg = row.get("message") or {}
    c = msg.get("content")
    text = c if isinstance(c, str) else "\n".join(
        str(b.get("text")) for b in (c or []) if isinstance(b, dict) and b.get("type") == "text"
    )
    print(f"type={row.get('type')} origin={json.dumps(row.get('origin'))}")
    print(text[:600])
    break
PY
  local line1
  line1="$(sed -n 3p "$CAPS/wake-evidence.txt" | head -c 160)"
  if grep -q 'quota-report: done rc=0' "$CAPS/wake-evidence.txt"; then
    record MATCH WAKE "idle session started a turn by itself; transcript row: $line1"
  else
    record MISMATCH WAKE "wake text present but wrong: $line1"
  fi
}

# ---- the run ------------------------------------------------------------------

echo "probe-lead run  $(date '+%Y-%m-%d %H:%M:%S')"
echo "mod: $MOD   work dir: $WD"

mode="${1:-all}"
if [ "$mode" = wake ]; then
  check_wake
elif [ "$mode" = all ]; then
  check_a1
  check_a2
  check_a4
  check_a5
  check_a3
else
  for c in "$@"; do
    case "$c" in
      A1) check_a1 ;;
      A2) check_a2 ;;
      A3) check_a3 ;;
      A4) check_a4 ;;
      A5) check_a5 ;;
      *) echo "unknown check: $c (A1 A2 A3 A4 A5, or wake)" >&2; exit 2 ;;
    esac
  done
fi

echo
echo "════════ probe-lead summary ════════"
for i in "${!CHECKS[@]}"; do
  printf '%s  %s  %s\n' "${VERDICTS[$i]}" "${CHECKS[$i]}" "${NOTES[$i]}"
done
fails=0
for v in "${VERDICTS[@]}"; do [ "$v" = MATCH ] || fails=$((fails + 1)); done
if [ "$fails" -eq 0 ]; then
  echo "all green"
  exit 0
fi
echo "FAILED: $fails check(s)"
exit 1
